[package]
name = "rust_raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.10"
impl_ops = "0.1.1"
serde = { version="1.0.195", features = ["derive"] }
toml = "0.8.8"